version: 0.2

phases:
  install:
    commands:
      - echo install phase started on `date`
      - python3 --version
      - 'curl -O https://bootstrap.pypa.io/pip/3.4/get-pip.py'
      - python3 get-pip.py
      - pip install --upgrade pip
      - python -m pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
